# Generated by Django 6.0.5 on 2026-05-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OPERATOR', 'Operator'), ('SUPERVISOR', 'Supervisor'), ('MANAGER', 'Manager')], default='OPERATOR', max_length=20, verbose_name='Role'),
        ),
    ]
